### PR TITLE
Add Rust for pyca/cryptography 3.4

### PR DESCRIPTION
**Pull request by mamercad**
See this issue: https://github.com/pyca/cryptography/issues/5771
And the changelog: https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst#34---2021-02-07

Sorry for the "docker stuff" in the commit history, I branched from something else I was doing.

### CODE REVIEW

**Comment by waweber** [comment]
:+1:, the image does not currently build.

A suggestion though: you can add the build dependencies to the `apk --update add --virtual` line so they will get removed after the python packages get installed.

**Comment by mamercad** [comment]
> , the image does not currently build.
> 
> A suggestion though: you can add the build dependencies to the `apk --update add --virtual` line so they will get removed after the python packages get installed.

Ah nice catch, pushed.

**Comment by mamercad** [comment]
> > , the image does not currently build.
> > A suggestion though: you can add the build dependencies to the `apk --update add --virtual` line so they will get removed after the python packages get installed.
> 
> Ah nice catch, pushed.

And, I see the build error as well:

```ash
+ apk --update add --virtual build-dependencies build-base python3-dev libffi-dev openssl-dev
ERROR: unable to select packages:
  gcc-20210326.173309:
    breaks: g++-10.2.1_pre1-r3[gcc=10.2.1_pre1-r3]
    satisfies: world[gcc=20210326.173309]
               rust-1.47.0-r2[gcc]
               build-base-0.5-r2[gcc]
The command '/bin/sh -c set -eux;     apk --update add bash openssh-client ruby git ruby-json python3 py3-pip openssl ca-certificates;     apk --update add --virtual gcc musl-dev cargo;     apk --update add --virtual       build-dependencies       build-base       python3-dev       libffi-dev       openssl-dev;     pip3 install --upgrade pip cffi;     pip3 install ansible boto pywinrm;     apk del build-dependencies;     rm -rf /var/cache/apk/*;     mkdir -p /etc/ansible;     echo -e "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts' returned a non-zero code: 6
```

**Comment by troykinsella** [comment]
Thanks for the contributions!

**Comment by mamercad** [comment]
The image built for me a few minutes ago (locally).

**Pull request merged**
